---
apiVersion: v1
kind: Service
metadata:
  name: vector
  namespace: monitoring
  labels:
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vector
    app.kubernetes.io/component: Agent
  annotations:
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vector
    app.kubernetes.io/component: Agent
  ports:
    - name: vector
      port: 6000
      protocol: TCP
